# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45d4965ad09c5de9ad3923c6c5d56f8e07ad7e24f1af1b5bb2afcc079fd555c08c7f699d3536b73f13b9d4a8ff6ce905b0044bc80f8110cd85fd6b8b9037a730

test:
  secret_key_base: bed97d0764ffcb21086d4225fb7234491df6066589066e8292b1c614ce5cae50489722121770974c6052f30ed9914bb5faeb0f9f49ce15564b79aa472a2529d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
